# ==============================
# 中文设置 (默认语言)
# ==============================
[zh-cn]
  languageName = "中文"
  weight = 1
  title = "E6D0的博客" # 请修改为你的博客标题

  [zh-cn.params]
    description = "中文描述"
    [zh-cn.params.sidebar]
      subtitle = "编码 & 生活"

# ==============================
# 英文设置 (English)
# ==============================
[en]
  languageName = "English"
  languageCode = "en-us"
  weight = 2
  title = "E6D0's Blog" # 请修改为你的英文博客标题

  [en.params]
    description = "English Description"
    [en.params.sidebar]
      subtitle = "Coding & Life"